### ISSUE TITLE
How can I load BFM_model?

### ISSUE THREAD

**Issue by levanpon98** [yiyuan1991/3D-Face-GCNs#10]
I load BFM09 but I have no file bfm2009_4seg.mat, bfm2009_face_idx.mat, how can I get those file?

**Comment by deepmo24** [comment]
Face the same problem( as well as bfm2009_symlist.txt). We cannot run the code without these necessary files. Wish the author  share more information about it.

**Comment by deepmo24** [comment]
@levanpon98 Hi, before loading "bfm2009_4seg.mat" and "bfm2009_face_idx.mat", we need to load "bfm2009_face.mat" first, do you know how to get this file? Thank you.

**Comment by HaoKun-Li** [comment]
It's a wonderful work but I face the same problem, too. I really hope to get these files or the way to generate them, thanks.

**Comment by deepmo24** [comment]
I have finded all these files from [BFM09](https://faces.dmi.unibas.ch/bfm/main.php?nav=1-0&id=basel_face_model) and [Deep3DFaceReconstruction](https://github.com/microsoft/Deep3DFaceReconstruction).

`bfm2009_4seg.mat  --> face05_4seg.mat (BFM09)`
`bfm2009_symlist.txt --> face05_symlist.txt (BFM09)`
`bfm2009_face_idx.mat --> select_vertex_id.mat (Deep3DFaceReconstruction)`
`bfm2009_face.mat --> BFM_model_front.mat (Deep3DFaceReconstruction)`

**Comment by HOMGH** [comment]
> I have finded all these files from [BFM09](https://faces.dmi.unibas.ch/bfm/main.php?nav=1-0&id=basel_face_model) and [Deep3DFaceReconstruction](https://github.com/microsoft/Deep3DFaceReconstruction).
> 
> `bfm2009_4seg.mat --> face05_4seg.mat (BFM09)`
> `bfm2009_symlist.txt --> face05_symlist.txt (BFM09)`
> `bfm2009_face_idx.mat --> select_vertex_id.mat (Deep3DFaceReconstruction)`
> `bfm2009_face.mat --> BFM_model_front.mat (Deep3DFaceReconstruction)`

@deepmo24
Hi Langyuan , Thank you so much for sharing what you found! Just wondering could you train their model? Does it converge?

**Comment by deepmo24** [comment]
@HOMGH Hi, I trained the model, but can't converge...... The result is not as good as they show in the paper.  What about you?

**Comment by HOMGH** [comment]
> @HOMGH Hi, I trained the model, but can't converge...... The result is not as good as they show in the paper. What about you?
Hi, I trained the model with 30,000 images and 20 epochs and the figure of total loss is as follows:
![image](https://user-images.githubusercontent.com/65192528/91634896-de34c800-e9a8-11ea-8ee4-3efa4041a99a.png)

Also I'm getting almost similar 3D mesh (geometry) for every input image I feed in the network. Attached are some 3D mesh examples (even with distortion, the base of 3D mesh looks the same). I'm considering the (output of shape decoder)*std + mean, as the final vertices to make 3D mesh. Do you think its correct?
![111](https://user-images.githubusercontent.com/65192528/91635035-e9d4be80-e9a9-11ea-8cee-258bbf0e3f8e.PNG)
![222](https://user-images.githubusercontent.com/65192528/91635038-ee00dc00-e9a9-11ea-892a-4f3f5809b707.PNG)
![333](https://user-images.githubusercontent.com/65192528/91635039-efca9f80-e9a9-11ea-976d-2632ca119980.PNG)

**Comment by HOMGH** [comment]
> @HOMGH Hi, I trained the model, but can't converge...... The result is not as good as they show in the paper. What about you?

Not yet. Do you mind share some of the results here? 
Thanks

**Comment by HOMGH** [comment]
> @HOMGH Hi, I trained the model, but can't converge...... The result is not as good as they show in the paper. What about you?

Hi @deepmo24 , By not converging, you mean the model is not able to  reconstruct 3D face? or just the results are not the same with the papers figures?

**Comment by deepmo24** [comment]
Hi, I mean the reconstructed texture is not that high fidelity as the paper showed.

**Comment by HOMGH** [comment]
> Hi, I mean the reconstructed texture is not that high fidelity as the paper showed.

Thanks, But at least you are getting roughly correct reconstructed texture and 3D mesh, right? coz in Nonlinear Face 3DMM model https://github.com/tranluan/Nonlinear_Face_3DMM, by training the model, I'm getting the same 3D meshes and textures for every input I feed in the model!

**Comment by HOMGH** [comment]
> Hi, I mean the reconstructed texture is not that high fidelity as the paper showed.

Hi @deepmo24 , do you mind sharing your test code you used for testing this model please?
Thanks.

**Comment by deepmo24** [comment]
@HOMGH Hi, I only runned the training code.

**Comment by HOMGH** [comment]
> @HOMGH Hi, I only runned the training code.
Aha, so you got the results by validation, right? would you please share some of the reconstructed faces with me? I'm actually going to run the training code, but before that, I just wanted to make sure it would result in at least some reasonable outputs!
Thanks.

**Comment by HOMGH** [comment]
> I have finded all these files from [BFM09](https://faces.dmi.unibas.ch/bfm/main.php?nav=1-0&id=basel_face_model) and [Deep3DFaceReconstruction](https://github.com/microsoft/Deep3DFaceReconstruction).
> 
> `bfm2009_4seg.mat --> face05_4seg.mat (BFM09)`
> `bfm2009_symlist.txt --> face05_symlist.txt (BFM09)`
> `bfm2009_face_idx.mat --> select_vertex_id.mat (Deep3DFaceReconstruction)`
> `bfm2009_face.mat --> BFM_model_front.mat (Deep3DFaceReconstruction)`

Hi @deepmo24,  where can I find bfm2009_face.mat which is used in the following line:
self.bfm = utils.BFM_model(self.root_dir, 'data/bfm2009_face.mat')

I couldn't find in BFM09 repository!

**Comment by deepmo24** [comment]
Hi, @HOMGH 
BFM09 is not a repository, it is from [BFM09](https://faces.dmi.unibas.ch/bfm/main.php?nav=1-0&id=basel_face_model).
One result is showed below:
![图片1](https://user-images.githubusercontent.com/19352002/92350654-376ccc00-f10c-11ea-9575-492220a13252.png)

**Comment by HOMGH** [comment]
> Hi, @HOMGH
> BFM09 is not a repository, it is from [BFM09](https://faces.dmi.unibas.ch/bfm/main.php?nav=1-0&id=basel_face_model).
> One result is showed below:
> ![图片1](https://user-images.githubusercontent.com/19352002/92350654-376ccc00-f10c-11ea-9575-492220a13252.png)

Yeah, I see, but I can't find this **bfm2009_face.mat** there.
And regarding the results, is it the final output of 3D-face_GCN method? :O

**Comment by deepmo24** [comment]
oh.... bfm2009_face.mat is gotten from Deep3DFaceReconstruction repo, by running `demo.py` (refer to [here](https://github.com/microsoft/Deep3DFaceReconstruction/blob/4b27ddf4227c687b953caa7aa3f3e7acf87cc786/demo.py#L31)).
Yes, it is the final output of 3D-face_GCN method.

**Comment by HOMGH** [comment]
> oh.... bfm2009_face.mat is gotten from Deep3DFaceReconstruction repo, by running `demo.py` (refer to [here](https://github.com/microsoft/Deep3DFaceReconstruction/blob/4b27ddf4227c687b953caa7aa3f3e7acf87cc786/demo.py#L31)).
> Yes, it is the final output of 3D-face_GCN method.

Sorry, I didn't get you. I ran the demo code from Deep3DFaceReconstruction repo, but still dunno where to get bfm2009_face.mat?

**Comment by deepmo24** [comment]
Rename BFM_model_front.mat to bfm2009_face.mat. They are exactly the same file.

**Comment by HOMGH** [comment]
> Rename BFM_model_front.mat to bfm2009_face.mat. They are exactly the same file.

Aha,ok. Thanks heaps 👍 Btw, the results you shared look good but as you said not as good as the reported results in the paper!

**Comment by HOMGH** [comment]
> Rename BFM_model_front.mat to bfm2009_face.mat. They are exactly the same file.

Hi @deepmo24 , while running the main.py, I'm getting this error. indices[23502] = 46328 is not in [0, 35709)
	 [[{{node loss_1/data_loss/GatherV2_2}}]].  Do you think something is wrong with bfm2009_symlist.txt or other files?

**Comment by HOMGH** [comment]
> Hi, @HOMGH
> BFM09 is not a repository, it is from [BFM09](https://faces.dmi.unibas.ch/bfm/main.php?nav=1-0&id=basel_face_model).
> One result is showed below:
> ![图片1](https://user-images.githubusercontent.com/19352002/92350654-376ccc00-f10c-11ea-9575-492220a13252.png)

Hi @deepmo24 , @FuxiCV , I'm just wondering, for training, should we use **aligned** celebA dataset as the input of the model or the original celebA images? Attached are aligned and unaligned samples.
![align](https://user-images.githubusercontent.com/65192528/93020111-47633080-f590-11ea-8839-d22706ce9901.PNG)
![333](https://user-images.githubusercontent.com/65192528/93020119-50540200-f590-11ea-82f2-e5b28ec05945.PNG)

Actually I used aligned celebA and I'm getting the following results after a couple of iterations, which I think are not correct and there should be sth wrong as the mask and landmarks and rendered are not overlaid correctly on the face!
![bb](https://user-images.githubusercontent.com/65192528/93020181-9741f780-f590-11ea-8726-24b8832a1b26.PNG)
![aa](https://user-images.githubusercontent.com/65192528/93020185-9a3ce800-f590-11ea-9d24-f0ebd798a86e.PNG)
![cc](https://user-images.githubusercontent.com/65192528/93020187-9c06ab80-f590-11ea-8513-97405ae6f4e9.PNG)
![dd](https://user-images.githubusercontent.com/65192528/93020190-9dd06f00-f590-11ea-83ac-3d5048ba4723.PNG)
![ff](https://user-images.githubusercontent.com/65192528/93020328-3666ef00-f591-11ea-87b1-f0223f20fb1e.PNG)

**Comment by FuxiCV** [comment]
Hey, as we mentioned in our paper, the input images should be aligned based on the facial landmarks. Since our method is based on the Deep3DFaceReconstruction, we adopt their alignment method https://github.com/microsoft/Deep3DFaceReconstruction/blob/master/preprocess_img.py in our codes.

**Comment by HOMGH** [comment]
Thanks @FuxiCV , but the process of preparing training set is still vague. Based on what you mentioned in your "ReadMe" file, 
1) I segmented the celebA dataset (I used img_align_celebA_png.7z as the training data NOT img_celebA.7z),
2) Stored the RGBA images as .png file. 
3) For efficiency, wrote all .png images into a binary file (using creat_bin),
So is it what should be done or I need to add that https://github.com/microsoft/Deep3DFaceReconstruction/blob/master/preprocess_img.py to the procedure?
Would you please clarify this?

**Comment by HOMGH** [comment]
> Thanks @FuxiCV , but the process of preparing training set is still vague. Based on what you mentioned in your "ReadMe" file,
> 
> 1. I segmented the celebA dataset (img_align_celebA_png.7z),
> 2. Stored the RGBA images as .png file.
> 3. For efficiency, wrote all .png images into a binary file (using creat_bin),
>    So is it what should be done or I need to add that https://github.com/microsoft/Deep3DFaceReconstruction/blob/master/preprocess_img.py to the procedure?

@deepmo24  Hi Langyuan, Any idea about this issue? Is that the same as you did?

**Comment by deepmo24** [comment]
Yes, I use this method to align the dataset.  I suggest that before segmenting the datasetset, you can align the dataset first.

**Comment by HOMGH** [comment]
> Yes, I use this method to align the dataset. I suggest that before segmenting the datasetset, you can align the dataset first.

Thanks @deepmo24 , So you mean you used celebA_img.7z (NOT img_align_celebA_png.7z? coz there are two types of data in celebA dataset) and then used https://github.com/microsoft/Deep3DFaceReconstruction/blob/master/preprocess_img.py to align the dataset?
Would you please share that part of code you used for alignment, as I'm not sure about the inputs of these functions? 
def POS(xp,x):
def process_img(img,lm,t,s,target_size = 224.):
def Preprocess(img,lm,lm3D):


Thanks.

**Comment by deepmo24** [comment]
Just use  img_align_celebA_png.7z I think.
I suggest you read  this part of code carefully (containing the aligning code)  https://github.com/FuxiCV/3D-Face-GCNs/blob/2c4459cfa05faaf82ef85994a696e79d2993d650/utils.py#L217

**Comment by HOMGH** [comment]
> Just use img_align_celebA_png.7z I think.
> I suggest you read this part of code carefully (containing the aligning code)
> 
> https://github.com/FuxiCV/3D-Face-GCNs/blob/2c4459cfa05faaf82ef85994a696e79d2993d650/utils.py#L217

Thanks @deepmo24 , Should we use groundtruth landmarks as well as face images?

@FuxiCV , whould you please clarify what dataset should we exactly use for training your model? celebA_img.7z or  img_align_celebA_png.7z?

**Comment by deepmo24** [comment]
We don't need to provide landmarks. The landmarks can be  detected by the landmark detector.

**Comment by HOMGH** [comment]
> We don't need to provide landmarks. The landmarks can be detected by the landmark detector.

Hi Langyuan @deepmo24 , 
I had a question, Do you know how to quantitatively evaluate the geometry reconstruction ability of this method? For CelebA we don't have any 3D ground truth. But for AFLW2000 that has 3D groundtruth, how can we do this? coz by this method we have 35,709 vertices. but for AFLW2000 the number of vertices is 53k (or 39k for reduced version). Any idea about that?
Thanks :)

**Comment by cyjouc** [comment]
> > I have finded all these files from [BFM09](https://faces.dmi.unibas.ch/bfm/main.php?nav=1-0&id=basel_face_model) and [Deep3DFaceReconstruction](https://github.com/microsoft/Deep3DFaceReconstruction).
> > `bfm2009_4seg.mat --> face05_4seg.mat (BFM09)`
> > `bfm2009_symlist.txt --> face05_symlist.txt (BFM09)`
> > `bfm2009_face_idx.mat --> select_vertex_id.mat (Deep3DFaceReconstruction)`
> > `bfm2009_face.mat --> BFM_model_front.mat (Deep3DFaceReconstruction)`
> 
> Hi @deepmo24, where can I find bfm2009_face.mat which is used in the following line:
> self.bfm = utils.BFM_model(self.root_dir, 'data/bfm2009_face.mat')
> 
> I couldn't find in BFM09 repository!

Hi, Do you madify name of the right file to name of the left file?I couldn't find the BFM_model_front.mat  in BFM09 repository but find the BFM_front_idx? Is it?

**Comment by cyjouc** [comment]
> > We don't need to provide landmarks. The landmarks can be detected by the landmark detector.
> 
> Hi Langyuan @deepmo24 ,
> I had a question, Do you know how to quantitatively evaluate the geometry reconstruction ability of this method? For CelebA we don't have any 3D ground truth. But for AFLW2000 that has 3D groundtruth, how can we do this? coz by this method we have 35,709 vertices. but for AFLW2000 the number of vertices is 53k (or 39k for reduced version). Any idea about that?
> Thanks :)

Hi,do you successfully prepear for the datasets?Counld you share the code?

**Comment by HOMGH** [comment]
> > > We don't need to provide landmarks. The landmarks can be detected by the landmark detector.
> > 
> > 
> > Hi Langyuan @deepmo24 ,
> > I had a question, Do you know how to quantitatively evaluate the geometry reconstruction ability of this method? For CelebA we don't have any 3D ground truth. But for AFLW2000 that has 3D groundtruth, how can we do this? coz by this method we have 35,709 vertices. but for AFLW2000 the number of vertices is 53k (or 39k for reduced version). Any idea about that?
> > Thanks :)
> 
> Hi,do you successfully prepear for the datasets?Counld you share the code?

Hi, please refer to https://github.com/FuxiCV/3D-Face-GCNs/issues/19#issue-707509376

**Comment by cyjouc** [comment]
> > > > We don't need to provide landmarks. The landmarks can be detected by the landmark detector.
> > > 
> > > 
> > > Hi Langyuan @deepmo24 ,
> > > I had a question, Do you know how to quantitatively evaluate the geometry reconstruction ability of this method? For CelebA we don't have any 3D ground truth. But for AFLW2000 that has 3D groundtruth, how can we do this? coz by this method we have 35,709 vertices. but for AFLW2000 the number of vertices is 53k (or 39k for reduced version). Any idea about that?
> > > Thanks :)
> > 
> > 
> > Hi,do you successfully prepear for the datasets?Counld you share the code?
> 
> Hi, please refer to [#19 (comment)](https://github.com/FuxiCV/3D-Face-GCNs/issues/19#issue-707509376)

how do you obtain the the fllowing three data?hicaicaihi for my wechat,Can you share the experiments for testing the model.
train_txt = '{}_train.txt'.format(prefix)
val_txt = '{}_val.txt'.format(prefix)
test_txt = '{}

**Comment by yaelfregier** [comment]
> > We don't need to provide landmarks. The landmarks can be detected by the landmark detector.
> 
> Hi Langyuan @deepmo24 ,
> I had a question, Do you know how to quantitatively evaluate the geometry reconstruction ability of this method? For CelebA we don't have any 3D ground truth. But for AFLW2000 that has 3D groundtruth, how can we do this? coz by this method we have 35,709 vertices. but for AFLW2000 the number of vertices is 53k (or 39k for reduced version). Any idea about that?
> Thanks :)

Hi Pingu @HOMGH,

I do not know if you managed to solve your problem, but my initial guess would be to apply this downsampling function to AFLW2000 
https://github.com/FuxiCV/3D-Face-GCNs/blob/2c4459cfa05faaf82ef85994a696e79d2993d650/lib/mesh_sampling.py#L97

**Comment by Msj5** [comment]
Did you train with main.py? Did you suffer out of memory?Could you share your train.py with me?plz reply to 3180532485@qq.com  
 thx. @deepmo24

**Comment by RodneyPerhaps** [comment]
> Hi, @HOMGH
> BFM09 is not a repository, it is from [BFM09](https://faces.dmi.unibas.ch/bfm/main.php?nav=1-0&id=basel_face_model).
> One result is showed below:
> ![图片1](https://user-images.githubusercontent.com/19352002/92350654-376ccc00-f10c-11ea-9575-492220a13252.png)

Hello, DeepMo! I'm glad you've succeeded to train and test the 3D face GCN method. Could you please share your pretrained model please? Thank you!

**Comment by biga-bomb** [comment]
> Hello, DeepMo! I'm glad you've succeeded to train and test the 3D face GCN method. Could you please share your pretrained model please? Thank you!

Hello, DeepMo! Could you please share your pretrained model please? Thank you very much!

**Comment by biga-bomb** [comment]
> We don't need to provide landmarks. The landmarks can be detected by the landmark detector.

Hello, DeepMo!  Could you please share your pretrained model please? Thank you very much!

**Comment by biga-bomb** [comment]
> We don't need to provide landmarks. The landmarks can be detected by the landmark detector.

Hello, DeepMo! Could you please share your pretrained model please? Thank you very much! 1154225766@qq.com

**Comment by haoxurt** [comment]
@deepmo24 Thank you for sharing your results. Did your model converge finally?

**Comment by haoxurt** [comment]
@deepmo24 Thank you for sharing your results. Did your model converge finally?  Btw, how did install `spatialsearch`?

**Comment by HDYYZDN** [comment]
> > 将 BFM_model_front.mat 重命名为 bfm2009_face.mat。它们是完全相同的文件。
> 
> 嗨@deepmo24，在运行 main.py 时，我收到此错误。索引 [23502] = 46328 不在 [0， 35709）[[{{node loss_1/data_loss/GatherV2_2}}]] 中。您认为bfm2009_symlist.txt或其他文件有问题吗？

想请问一下，您是如何解决的呢 ，针对对称索引，不在 [0， 35709]中

**Comment by HathawayNoa79** [comment]
> Hi, where can I get the torch_FaceSegment_300.pkl？Can you share the torch_FaceSegment_300.pkl with me?
