### ISSUE TITLE
where to get bfm2009_face.mat?

### ISSUE THREAD

**Issue by HOMGH** [yiyuan1991/3D-Face-GCNs#17]
Hi, where can I find  **bfm2009_face.mat** which is used in the following:
    self.bfm = utils.BFM_model(self.root_dir, 'data/bfm2009_face.mat')

I couldn't find in BFM09 repository!

**Comment by FuxiCV** [comment]
Hi, sorry for the inconvenience, some of the files come from:
bfm2009_4seg.mat -- face05_4seg.mat (https://faces.dmi.unibas.ch/bfm/?nav=1-0&id=basel_face_model)
bfm2009_symlist.txt -- face05_symlist.txt (https://faces.dmi.unibas.ch/bfm/?nav=1-0&id=basel_face_model)
bfm2009_face_idx.mat -- select_vertex_id.mat (https://github.com/microsoft/Deep3DFaceReconstruction)
bfm2009_face.mat -- BFM_model_front.mat (https://github.com/microsoft/Deep3DFaceReconstruction)
