### ISSUE TITLE
What is FaceReconModel.pb in the code?

### ISSUE THREAD

**Issue by HOMGH** [yiyuan1991/3D-Face-GCNs#4]
Hi,
Thanks for sharing your source code. There is FaceReconModel.pb in base.model.py It seems that it should be in data folder. Where can I find it?

**Comment by FuxiCV** [comment]
Sorry we didn’t make it clear, it is the pre-trained model from https://github.com/microsoft/Deep3DFaceReconstruction, please refer to their project page for the necessary files.
We will update the readme file in the future.

**Comment by HOMGH** [comment]
> Sorry we didn’t make it clear, it is the pre-trained model from https://github.com/microsoft/Deep3DFaceReconstruction, please refer to their project page for the necessary files.
> We will update the readme file in the future.

Found it! Thank you very much.
