### ISSUE TITLE
where to get bfm09_face_template.obj?

### ISSUE THREAD

**Issue by HOMGH** [yiyuan1991/3D-Face-GCNs#7]
Hi
It seems that we need **bfm09_face_template.obj** for running the main.py file. Where should I download this file?

**Comment by FuxiCV** [comment]
Hi
You can create the bfm09_face_template.obj by:
```
  import numpy as np
  import scipy.io as sio
  from lib import mesh_io

  bfm = sio.loadmat('data/01_MorphableModel.mat')
  idx = sio.loadmat('data/select_vertex_id.mat')
  info = sio.loadmat('data/facemodel_info.mat')

  vertices = bfm['shapeMU'].reshape([-1, 3])[idx['select_id'][:, 0] - 1]
  vertices -= np.mean(vertices, axis=0, keepdims=True)
  mesh_io.write_obj('data/bfm09_face_template.obj', vertices / 1e5,
                    info['tri'].astype(np.int32) - 1)
```
where the `01_MorphableModel.mat` is from [BFM09](https://faces.dmi.unibas.ch/bfm/main.php?nav=1-2&id=downloads), `select_vertex_id.mat` and `facemodel_info.mat` are from [Deep3DFaceReconstruction](https://github.com/microsoft/Deep3DFaceReconstruction).

**Comment by yuxwind** [comment]
Just note that select_vertex_id.mat and facemodel_info.mat are udner BFM directory in Deep3DFaceReconstruction.

**Comment by HOMGH** [comment]
> Just note that select_vertex_id.mat and facemodel_info.mat are udner BFM directory in Deep3DFaceReconstruction.

Thanks.
Another question is that how to quantitatively evaluate the geometry reconstruction ability of this method? For CelebA we don't have any 3D ground truth. But for AFLW2000 that has 3D groundtruth, how can we do this? coz by this method we have 35,709 vertices. but for AFLW2000 the number of vertices is 53k (or 39k for reduced version). Any idea about that?
Thanks :)
