### ISSUE TITLE
How can I acquire the files such as bfm2009_face.mat when I load BFM model?

### ISSUE THREAD

**Issue by zhuort** [yiyuan1991/3D-Face-GCNs#8]
I downloaded the BFM2009 model from the offical website, but I think they can't be used directly.

**Comment by FuxiCV** [comment]
Hi, sorry for the inconvenience, some of the files come from:
bfm2009_4seg.mat -- face05_4seg.mat (https://faces.dmi.unibas.ch/bfm/?nav=1-0&id=basel_face_model)
bfm2009_symlist.txt -- face05_symlist.txt (https://faces.dmi.unibas.ch/bfm/?nav=1-0&id=basel_face_model)
bfm2009_face_idx.mat -- select_vertex_id.mat (https://github.com/microsoft/Deep3DFaceReconstruction)
bfm2009_face.mat -- BFM_model_front.mat (https://github.com/microsoft/Deep3DFaceReconstruction)
